sudo: required 

services:
  - docker

before_install:
  - docker build -t shankarbk/react-test -f ./client/Dockerfile.dev .client

script:
  - docker run -e CI=true shankarbk/react-test npm test

after_success:
  - docker build -t shankarbk/multiple-client ./client
  - docker build -t shankarbk/multiple-nginx ./nginx
  - docker build -t shankarbk/multiple-server ./server
  - docker build -t shankarbk/multiple-worker ./worker
  
# login to doccker CLI

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push shankarbk/multiple-client
  - docker push shankarbk/multiple-nginx
  - docker push shankarbk/multiple-server
  - docker push shankarbk/multiple-worker


