version: '3'
services:
  postgres_s:
    image: 'postgres:latest'
    environment:
      - POSTGRES_PASSWORD=postgres_password
  redis_s:
    image: 'redis:latest'
  nginx_s:
    depends_on:
      - server_s
      - client_s
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3000:80'
  server_s:
    depends_on:
      - postgres_s
    build: 
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - REDIS_HOST=redis_s
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres_s
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
  client_s:
    stdin_open: true
    build:
      dockerfile: Dockerfile.dev
      context: ./client 
    volumes:
      - /app/node_modules
      - ./client:/app
  worker_s:
    build:
      dockerfile: Dockerfile.dev
      context: ./worker 
    volumes:
      - /app/node_modules
      - ./worker:/app
